AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Discord Bot with Request Verification and Command Handling

Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  DiscordBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: verify_request.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Events:
        BotCalls:
          Type: Api
          Properties:
            Path: /
            Method: POST
      Layers:
        - !Ref DependenciesLayer

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: dependencies-layer
      Description: "Contains Python dependencies"
      ContentUri: package/
      CompatibleRuntimes:
        - python3.10
      RetentionPolicy: Delete

  DiscordBotAPI:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod
      CorsConfiguration:
        AllowMethods:
          - POST
        AllowHeaders:
          - Content-Type
          - X-Signature-Ed25519
          - X-Signature-Timestamp
        AllowOrigins:
          - "*"
      AccessLogSettings:
        DestinationArn: !GetAtt DiscordBotAPILogGroup.Arn
        Format: '$context.requestId $context.httpMethod $context.path $context.status $context.responseLength'

  DiscordBotAPILogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/http-api/${DiscordBotAPI}"
      RetentionInDays: 7

Outputs:
  BotApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${DiscordBotAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
